apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: app-k8s

spec:
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app-k8s
  template:
    metadata:
      labels:
        app: app-k8s
    template:
      spec:
        containers:
          - name: app-k8s
            image: danielrodriguess/app-k8s:v4
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 3000
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
    strategy:
      # blueGreen:
        # autoPromotionEnabled: false
        # activeService: app-k8s-svc
        # previewService: app-k8s-preview
      canary:
        steps:
          - setWeight: 20
          - pause: { duration: 10 }
          - setWeight: 30
          - pause: { duration: 30 }
          - setWeight: 50
          - pause: { duration: 60 }
          - setWeight: 80
          - pause: { duration: 60 }